In [2]:
#Assignment 10.1A#

import string

def tokenize(sentence):
    # Split the sentence by spaces
    words = sentence.split()
    table = str.maketrans('', '', string.punctuation)
    stripped = [w.translate(table) for w in words]
    return stripped

sentence = "Good Morning, I hope you are having a great day Professor! Please give me an A+"
tokens = tokenize(sentence)
print(type(tokens))
print(tokens)

<class 'list'>
['Good', 'Morning', 'I', 'hope', 'you', 'are', 'having', 'a', 'great', 'day', 'Professor', 'Please', 'give', 'me', 'an', 'A']


In [3]:
#Assignmet 10.1B#
import string
import nltk

def ngram(tokens, n):
    # Split the sentence by spaces
    sentence = tokens.split()
    # Remove punctuation
    newtable = str.maketrans('', '', string.punctuation)
    stripped = [w.translate(newtable) for w in sentence]
    ngrams = nltk.ngrams(stripped, n)
    return ngrams

paragraph = "Fine Professor, I will take an A- instead! But, that is the lowest I am going!"
ngrams = ngram(sentence, 1)
for g in ngrams:
    print(g)

('Good',)
('Morning',)
('I',)
('hope',)
('you',)
('are',)
('having',)
('a',)
('great',)
('day',)
('Professor',)
('Please',)
('give',)
('me',)
('an',)
('A',)


In [4]:
#Assignment 10.1C#
import string
import nltk
from numpy import array
from numpy import argmax
from keras.utils import to_categorical


def one_hot_encode(tokens):
    results = array(tokens)
    print(results)
    results = to_categorical(data)
    return results

data = [1,2,4]
value = one_hot_encode(tokens)
print(value)

['Good' 'Morning' 'I' 'hope' 'you' 'are' 'having' 'a' 'great' 'day'
 'Professor' 'Please' 'give' 'me' 'an' 'A']
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
#Assignment 10.2#
#Not sure why I am getting an error, as I have this file#
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import os

from keras.models import Sequential
from keras.layers import Embedding, Flatten, Dense

imdb_dir = Path('dsc650/data/external/imdb/aclImdb')
training_samples = 100
maxlen = 50
max_words = 500
embedding_dim = 50
max_features = 1000



training_samples = 50
validation_samples = 100


model = Sequential()
model.add(Embedding(max_words, embedding_dim, input_length=maxlen))
model.add(Flatten())
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()
test_dir = os.path.join(imdb_dir, 'test')
labels = []
texts = []

for label_type in ['neg', 'pos']:
    dir_name = os.path.join(test_dir, label_type)
    for fname in sorted(os.listdir(dir_name)):
        if fname[-4:] == '.txt':
            f = open(os.path.join(dir_name, fname))
            texts.append(f.read())
            f.close()
            if label_type == 'neg':
                labels.append(0)
            else:
                labels.append(1)
x_train = data[:training_samples]
y_train = labels[:training_samples]
x_val = data[training_samples: training_samples + validation_samples]
y_val = labels[training_samples: training_samples + validation_samples]


model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['acc'])
history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_data=(x_val, y_val))




sequences = tokenizer.texts_to_sequences(texts)
x_test = pad_sequences(sequences, maxlen=maxlen)
y_test = np.asarray(labels)



model.load_weights('pre_trained_glove_model.h5')
model.evaluate(x_test, y_test)

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 50, 50)            25000     
_________________________________________________________________
flatten_1 (Flatten)          (None, 2500)              0         
_________________________________________________________________
dense_10 (Dense)             (None, 32)                80032     
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 33        
Total params: 105,065
Trainable params: 105,065
Non-trainable params: 0
_________________________________________________________________


FileNotFoundError: [Errno 2] No such file or directory: 'dsc650/data/external/imdb/aclImdb/test/neg'

In [16]:
#Assignment 10.3#
#It for some reason kept pulling up this error, I could not figure out how to solve it. From what I saw there is nothing online


from keras.layers import LSTM



input_train = data[:training_samples]
y_train = labels[:training_samples]
input_test = data[training_samples: training_samples + validation_samples]
y_test = labels[training_samples: training_samples + validation_samples]


model = Sequential()
model.add(Embedding(max_features, 32))
model.add(LSTM(32))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['acc'])
history = model.fit(input_train, y_train,
                    epochs=10,
                    batch_size=128,
                    validation_split=0.2)


ValueError: `validation_split` is only supported for Tensors or NumPy arrays, found following types in the input: [<class 'int'>, <class 'int'>, <class 'int'>]

In [18]:
from keras.models import Sequential
from keras import layers
from keras.optimizers import RMSprop

model = Sequential()
model.add(layers.Embedding(max_features, 128, input_length=max_len))
model.add(layers.Conv1D(32, 7, activation='relu'))
model.add(layers.MaxPooling1D(5))
model.add(layers.Conv1D(32, 7, activation='relu'))
model.add(layers.GlobalMaxPooling1D())
model.add(layers.Dense(1))

model.summary()

model.compile(optimizer=RMSprop(lr=1e-4),
              loss='binary_crossentropy',
              metrics=['acc'])
history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=128,
                    validation_split=0.2)

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_12 (Embedding)     (None, 500, 128)          1280000   
_________________________________________________________________
conv1d_6 (Conv1D)            (None, 494, 32)           28704     
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 98, 32)            0         
_________________________________________________________________
conv1d_7 (Conv1D)            (None, 92, 32)            7200      
_________________________________________________________________
global_max_pooling1d_3 (Glob (None, 32)                0         
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 33        
Total params: 1,315,937
Trainable params: 1,315,937
Non-trainable params: 0
___________________________________________